config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :post_comments
  resources :posts
  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end

  resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  post   '/users',     to: 'users#create',  as: 'users' #adds _path to as
  get    '/users/:id', to: 'users#show',    as: 'user'
  delete '/users/:id', to: 'users#destroy', as: 'destroy'
  patch  '/users/:id', to: 'users#update'

  get '/login',  to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  post '/sessions', to: 'sessions#create'

  post   '/spots',     to: 'spots#create'
  get    '/spots',     to: 'spots#index'
  post   '/spots',     to: 'spots#create'
  get    '/spots/:id', to: 'spots#show',    as: 'spot'
  delete '/spots/:id', to: 'spots#destroy', as: 'destroy_spot'
  patch  '/spots/:id', to: 'spots#update',  as: 'edit_spot'
  get    '/spots/new', to: 'spots#new',     as: 'new_spot'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = current_user.mailbox.conversations
  end

  def inbox
    @conversations = current_user.mailbox.inbox
    render action: :index
  end

  def sent
    @conversations = current_user.mailbox.sentbox
    render action: :index
  end

  def trash
    @conversations = current_user.mailbox.trash
    render action: :index
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
    @conversation.mark_as_read(current_user)
    @message = Mailboxer::Message.new
  end

  def new
    @conversation = Mailboxer::Conversation.new
    @recipients = User.all - [current_user]
  end

  def create
    recipients = User.where(id: params[:user_ids])
    receipt   = current_user.send_message(recipients, params[:body], params[:subject])
    redirect_to conversation_path(receipt.conversation)
    #redirect_to inbox_conversations_path
  end

  def destroy
    @conversation = current_user.mailbox.conversations.find(params[:id])
    @conversation.destroy
    redirect_to conversations_path
  end
end

app/views/conversations/index.html.erb
<%= render "shared/nav" %>
<div class="profiletwo">
  <%= link_to "New Message", new_conversation_path %>
</div>

<div class="post_header">
  <h1>Your Messages</h1>
</div>
<hr />
<div class="message">
  Inbox (<%= current_user.mailbox.inbox.unread(current_user).count %>) |
  All Messages (<%= current_user.mailbox.conversations.count %>) |
  Sent (<%= current_user.mailbox.sentbox.count %>) |
  <!-- Trash (<%= current_user.mailbox.trash.count %>) -->
</div>
<hr />
<div class="messagetwo">
  Total: (<%= @conversations.count %>)
</div>
<% @conversations.each do |conversation| %>
<div class="messages">
    <% if conversation.is_unread?(current_user) %>
      <strong><%= link_to conversation.subject, conversation_path(conversation) %></strong>
    <% else %>
      <%= link_to conversation.subject, conversation_path(conversation) %>
</div>
      <%= link_to 'Delete Message', conversation_path(conversation), method: :delete, data: { confirm: 'Are you sure?' } , class: "messagedelete"%>
    <% end %>
<%end%>

app/views/conversations/new.html.erb
<%= render "shared/nav" %>
<h1>New Conversation</h1>

<%= form_tag conversations_path, method: :post do %>
  <div class="message">
    <div class="input-field col s12">
      <%= select_tag :user_ids, options_from_collection_for_select(@recipients, :id, :username), multiple: true %>
      <label>Select which Users to Message</label>
    </div>
  </div>
  <div class="message">
    <p><%= text_field_tag :subject, nil, placeholder: "Subject" %></p>
  </div>
  <div class="message">
    <p><%= text_area_tag :body, nil, placeholder: "Leave a comment" %></p>
    <%= submit_tag %>
  </div>
<% end %>

app/views/conversations/show.html.erb
<%= render "shared/nav" %>
<h1> <%= @conversation.subject %> </h1>

<div class="message">
  <h4> Participants: </h4>
  <% @conversation.participants.each do |participant|%>
    <div> <%= participant.username %> </div>
  <% end %>
</div>

<div class="message">
  <% @conversation.receipts_for(current_user).each do |receipt|%>
    <div>
      <div> <%= receipt.message.sender.username %> commented: </div>
      <%= simple_format receipt.message.body %>
    </div>
  <% end %>
</div>

<div class="message">
  <%= form_for @message, url: conversation_messages_path(@conversation) do |f| %>
    Enter Comment:
    <div>
      <%= f.text_area :body %>
    </div>
    <%= f.submit %>
  <% end %>
</div>