config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :post_comments
  resources :posts
  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end

  resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  post   '/users',     to: 'users#create',  as: 'users' #adds _path to as
  get    '/users/:id', to: 'users#show',    as: 'user'
  delete '/users/:id', to: 'users#destroy', as: 'destroy'
  patch  '/users/:id', to: 'users#update'

  get '/login',  to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  post '/sessions', to: 'sessions#create'

  post   '/spots',     to: 'spots#create'
  get    '/spots',     to: 'spots#index'
  post   '/spots',     to: 'spots#create'
  get    '/spots/:id', to: 'spots#show',    as: 'spot'
  delete '/spots/:id', to: 'spots#destroy', as: 'destroy_spot'
  patch  '/spots/:id', to: 'spots#update',  as: 'edit_spot'
  get    '/spots/new', to: 'spots#new',     as: 'new_spot'

end

app/models/user.rb
class User < ApplicationRecord
  acts_as_messageable
  before_destroy { messages.destroy_all }

  has_many :post_comments
  has_many :posts
  has_many :spots
  has_secure_password

  has_many :friendships
  has_many :friends, :through => :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  validates :username, presence: true, uniqueness: true
  validates :email, uniqueness: true, presence: true
  validates :password, presence: true, length: { in: 6..20 }

  def name
    "User #{id}"
  end

  def mailboxer_email(object)
    nil
  end

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    login(@user)
    redirect_to @user
  end

  def show
    @user = User.find_by_id(params[:id])
  end
  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :gender, :sports, :self_description, :age, :username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_current_user, only: [:show]

  def index
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      login(@user)
      flash[:success] = "Successfully logged in."
      redirect_to @user
    else
      flash[:error] = "Incorrect information. Follow directions better."
      redirect_to root_path
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    @users = User.all
  end

  def update
    @user = User.find_by_id(session[:user_id])
    @user.update_attributes(user_params)
    redirect_to user_path(@user)
  end

  def edit
    @user = User.find_by_id(params[:user_id])
    if current_user.id != @post.user_id
      redirect_to post_path(@post)
    end
  end

  def destroy
    user = User.find_by_id(params[:user_id])
    user.destroy
    redirect_to root_url
  end

  private

  def is_current_user
    if current_user.id.to_s != params[:id]
      redirect_to user_path(current_user)
    end

  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :gender, :sports, :self_description, :age, :username, :image)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/index.html.erb
<body id="skatepic">

  <div class="container">
    <div class="row">
      <div class="col s12 hello">
        <div class="section brand-logo">
          <h1>Come Shred With Us!</h1>
          <h4>  &emsp; Come Shred is a community. A place to meet people to skate, bike, surf,
            rollerblade, and/or scooter with. More importantly, you can find new spots
            on our Map to shred, spots that you didn't know about before! You can add places
            that aren't on the Map too, helping our community to grow.</h4>
        </div>
        <div class="section">
          <a class="waves-effect waves-light btn modal-trigger" href="#modal_signup">Sign Up!</a>
          <a class="waves-effect waves-light btn modal-trigger" href="#modal_login">Login</a>
        </div>
      </div>
    </div>
  </div>
</body>
<%= render "shared/sign_up_login_modal" %>

app/views/users/show.html.erb
<%= render "shared/nav" %>

<div class="profile">
  <div class= "profile_img">
    <%= if @user.image == nil
      image_tag('http://weclipart.com/gimg/DE3DE279C8E11C7C/dc6o8deoi.jpeg')
    else
      image_tag(@user.image)
    end %>
  </div>
  <h4>Hey <%= @user.first_name %> <%= @user.last_name %>!</h4>
  <h6>Sports: <%= @user.sports %></h6>
  <h6>Age: <%= @user.age %></h6>
  <h6>Gender: <%= @user.gender %></h6>
  <h6>Username: <%= @user.username %></h6>
  <h6>Email: <%= @user.email %></h6>
  <h6>Self Description: <%= @user.self_description %></h6>
  <a class="waves-effect waves-light btn modal-trigger dude" href="#modal3">Edit Profile</a>
</div>


<%= render "shared/edit_profile" %>

<div class="profile">
  <h5>Friends To Add!</h5>
  <% for user in @users %>
    <div class="user">
      <p>
        <strong><%=h user.username %></strong>
        <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
        <div class="clear"></div>
      </p>
    </div>
  <% end %>
</div>

<!-- <div class="profile">
  <p>Username: <%=h @user.username %></p>
  <p><%= link_to "Find Friends", users_path %></p>
</div> -->

<div class="profile">
  <h5>Your Friends</h5>
  <ul>
    <% for friendship in @user.friendships %>
    <li>
      <%= h friendship.friend.username %>
      (<%= link_to "remove", friendship, :method => :delete %>)
    </li>
    <% end %>
  </ul>
</div>

<div class="profile">
  <h5>Users Who Have Befriended You</h5>
  <ul>
    <% for user in @user.inverse_friends %>
    <li><%= h user.username %></li>
    <% end %>
  </ul>
</div>
<div class="profiletwo">
  <%= link_to "Delete Profile", destroy_path(@user), data: {:confirm => "Are you sure you want to delete your profile?"}, :method => :delete %>
</div>