config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :post_comments
  resources :posts
  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end

  resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  post   '/users',     to: 'users#create',  as: 'users' #adds _path to as
  get    '/users/:id', to: 'users#show',    as: 'user'
  delete '/users/:id', to: 'users#destroy', as: 'destroy'
  patch  '/users/:id', to: 'users#update'

  get '/login',  to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  post '/sessions', to: 'sessions#create'

  post   '/spots',     to: 'spots#create'
  get    '/spots',     to: 'spots#index'
  post   '/spots',     to: 'spots#create'
  get    '/spots/:id', to: 'spots#show',    as: 'spot'
  delete '/spots/:id', to: 'spots#destroy', as: 'destroy_spot'
  patch  '/spots/:id', to: 'spots#update',  as: 'edit_spot'
  get    '/spots/new', to: 'spots#new',     as: 'new_spot'

end

app/views/shared/_add_spot.html.erb
<div id="modal_add" class="modal modal-fixed-footer">
  <%= form_for @spot do |f| %>
  <div class="modal-content">
    <div class="row">
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :latitude%>
          <label for="latitude">Enter Latitude</label>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :longitude%>
          <label for="longitude">Enter Longitude</label>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :address%>
        <label for="address">Enter Full Address, Including Country</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :name%>
        <label for="name">Give it A Name</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :features%>
        <label for="features">Features</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :comments%>
        <label for="comments">Comments</label>
      </div>
    </div>
    <!-- <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :rating%>
        <label for="rating">Rating</label>
      </div>
    </div> -->
  </div>
  <div class="modal-footer">
    <a class="modal-action modal-close waves-effect waves-red btn-flat">Cancel</a>
    <%= f.submit "Save", class: "btn-flat"%>
  </div>
  <%end%>
</div>

app/views/shared/_edit_profile.html.erb
<div id="modal3" class="modal sick">
  <div class="modal-content">
    <%= form_for @user, :class=> "col s12" do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :first_name %>
        <%= f.label :first_name, :class=> "active" %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :last_name %>
        <%= f.label :last_name, :class=> "active" %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
       <%= f.text_field :email %>
       <%= f.label :email, :class=> "active" %>
     </div>
   </div>
   <div class="row">
     <div class="input-field col s12">
       <%= f.text_field :password %>
       <%= f.label :password, :class=> "active" %>
     </div>
   </div>
   <div class="row">
     <div class="input-field col s12">
       <%= f.text_field :age %>
       <%= f.label :age, :class=> "active" %>
     </div>
   </div>
   <div class="row">
     <div class="input-field col s12">
       <%= f.text_field :gender %>
       <%= f.label :gender, :class=> "active" %>
     </div>
   </div>
   <div class="row">
     <div class="input-field col s12">
       <%= f.text_field :sports %>
       <%= f.label :sports, :class=> "active" %>
     </div>
   </div>
   <div class="row">
     <div class="input-field col s12">
      <%= f.text_field :username %>
      <%= f.label :username, :class=> "active" %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :self_description %>
      <%= f.label :self_description, :class=> "active" %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :image, placeholder: "Image Url"%>
    </div>
  </div>
    <div class="modal-footer">
      <a class="modal-action modal-close waves-effect waves-red btn-flat">Cancel</a>
      <%= f.submit "submit", :class=> "btn-flat" %>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="/posts" class="brand-logo left">ComeShred</a>
    <ul id="nav-mobile" class="right">
      <li><%= link_to "Profile Page", user_path(current_user[:id]), class: "btn waves-effect waves-light" %></li>
      <li><%= link_to "Spots", spots_path, class: "btn waves-effect waves-light" %></li>
      <li><%= link_to "Posts", posts_path, class: "btn waves-effect waves-light" %></li>
      <li><%= link_to "Messages", conversations_path, class: "btn waves-effect waves-light" %></li>
      <li><%= link_to "Log Out", logout_path, class: "btn waves-effect waves-light" %></li>
    </ul>
  </div>
</nav>

app/views/shared/_sign_up_login_modal.html.erb
<div id="modal_signup" class="modal modal-fixed-footer">
  <%= form_for @user do |f| %>
  <div class="modal-content">
    <div class="row">
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :first_name%>
          <label for="first_name">Enter First Name</label>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :last_name%>
          <label for="last_name">Enter Last Name</label>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :age%>
        <label for="age">Age</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :username%>
        <label for="username">Username, must be unique</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :gender%>
        <label for="gender">Gender</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :sports%>
        <label for="sports">Sports</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :self_description%>
        <label for="self_description">Self Description</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :image%>
        <label for="image">Enter Image Address</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :email%>
        <label for="email">Email</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.password_field :password%>
        <label for="password">Password, Must be between 6 to 20 Characters</label>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <a class="modal-action modal-close waves-effect waves-red btn-flat">Cancel</a>
    <%= f.submit "Save", class: "btn-flat"%>
  </div>
  <%end%>
</div>

<div id="modal_login" class="modal modal-fixed-footer">
  <% @user=User.new %>
  <%= form_for @user, url: "/sessions", method: "post" do |f| %>
  <div class="modal-content">
    <div class="row">
      <div class="input-field col s12">
        <%= f.email_field :email, placeholder: "Email" %>
        <label for="email">Email</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.password_field :password, placeholder: "Password" %>
        <label for="password">Password</label>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <a class="modal-action modal-close waves-effect waves-red btn-flat">Cancel</a>
    <%= f.submit "Login", class: "btn-flat" %>
  </div>
  <% end %>
</div>