config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :post_comments
  resources :posts
  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end

  resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  post   '/users',     to: 'users#create',  as: 'users' #adds _path to as
  get    '/users/:id', to: 'users#show',    as: 'user'
  delete '/users/:id', to: 'users#destroy', as: 'destroy'
  patch  '/users/:id', to: 'users#update'

  get '/login',  to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  post '/sessions', to: 'sessions#create'

  post   '/spots',     to: 'spots#create'
  get    '/spots',     to: 'spots#index'
  post   '/spots',     to: 'spots#create'
  get    '/spots/:id', to: 'spots#show',    as: 'spot'
  delete '/spots/:id', to: 'spots#destroy', as: 'destroy_spot'
  patch  '/spots/:id', to: 'spots#update',  as: 'edit_spot'
  get    '/spots/new', to: 'spots#new',     as: 'new_spot'

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_comments
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
    @post_comment = PostComment.new
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url}
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        #redirect_to posts_url redirect_to @post
        format.html { redirect_to posts_url }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:main, :comment, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :main %>
    <%= form.text_field :main, id: :post_main %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render "shared/nav" %>
<h1>Edit Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render "shared/nav" %>
<p id="notice"><%= notice %></p>

<div class="post_header">
  <h4>Post About New Tricks, New Spots, And New Events</h4>
</div>

  <%= link_to 'New Post', new_post_path, class: "btn waves-effect waves-light dudethree" %>

<div class="posts">

  <% @posts.each do |post| %>
    <div class="post">
      <h4><%= post.main %></h4>
      Post by: <%= post.user.username %>
    </div>
    <div class="post_buttons">
      <%= link_to 'Edit', edit_post_path(post) %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <hr />
      <% post.post_comments.each do |comment|%>
        <div class="comment">
           <h6>Comment: <%= comment.comment %></h6>
           Comment by: <%= comment.user.username %>
        </div>
        <div class="post_buttons">
          <!-- <%= link_to 'Edit', edit_post_comment_path(comment) %> -->
          <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
      <%= render :partial => "post_comments/comment_form", :locals => {:post_id => post.id }%>
      <a class="waves-effect waves-light btn modal-trigger dude" href="#modal_add_comment_<%= post.id %>">Comment</a>
    <hr />
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render "shared/nav" %>
<p id="notice"><%= notice %></p>
<p>
  <strong>Main:</strong>
  <%= @post.main %>
</p>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>